# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.AddField(
            model_name='book',
            name='text',
            field=mezzanine.core.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='dob',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
